

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE="REGISTER_USER_FIALURE"


export const LOGIN_REQEST = 'LOGINREQ';
export const LOGIN_SUCCESS ="LOGINSUCCESS";
export const LOGIN_FAILURE="LOGINFAILURE";


